name: Deploy to Serer

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
      - uses: actions/checkout@v3
      - name: Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install